### ISSUE TITLE
Second retry will have an undefined interval

### ISSUE THREAD

**Issue by naugtur** [SkPhilipp/Retry#1]
https://github.com/SkPhilipp/Retry/blob/master/retry.js#L15 skips passing interval down. Doesn't look deliberate. Or am I wrong?

**Comment by SkPhilipp** [comment]
You are completely correct, thanks for using and noticing. Fix is in place.

**Comment by naugtur** [comment]
I actually needed an exponential backoff strategy, so in the end I went on to implement it myself, but reading your code was encouraging. 

If you had thorough testing for this bit of code, I think it'd be a good idea to suggest building it into Q itself.
